#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PeoplePlusMobile.Resource", IsApplication=true)]

namespace PeoplePlusMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010019
			public const int civ_border_color = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int civ_border_overlay = 2130771994;
			
			// aapt resource value: 0x7f010018
			public const int civ_border_width = 2130771992;
			
			// aapt resource value: 0x7f01001b
			public const int civ_fill_color = 2130771995;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f01000a
			public const int fastScrollEnabled = 2130771978;
			
			// aapt resource value: 0x7f01000d
			public const int fastScrollHorizontalThumbDrawable = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int fastScrollHorizontalTrackDrawable = 2130771982;
			
			// aapt resource value: 0x7f01000b
			public const int fastScrollVerticalThumbDrawable = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int fastScrollVerticalTrackDrawable = 2130771980;
			
			// aapt resource value: 0x7f010016
			public const int font = 2130771990;
			
			// aapt resource value: 0x7f01000f
			public const int fontProviderAuthority = 2130771983;
			
			// aapt resource value: 0x7f010012
			public const int fontProviderCerts = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int fontProviderFetchStrategy = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int fontProviderFetchTimeout = 2130771988;
			
			// aapt resource value: 0x7f010010
			public const int fontProviderPackage = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int fontProviderQuery = 2130771985;
			
			// aapt resource value: 0x7f010015
			public const int fontStyle = 2130771989;
			
			// aapt resource value: 0x7f010017
			public const int fontWeight = 2130771991;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010006
			public const int layoutManager = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int reverseLayout = 2130771976;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int spanCount = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int stackFromEnd = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0a0000
			public const int abc_action_bar_embed_tabs = 2131361792;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06000f
			public const int common_google_signin_btn_text_dark = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int common_google_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int common_google_signin_btn_text_dark_disabled = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_signin_btn_text_dark_focused = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_signin_btn_text_dark_pressed = 2131099651;
			
			// aapt resource value: 0x7f060010
			public const int common_google_signin_btn_text_light = 2131099664;
			
			// aapt resource value: 0x7f060004
			public const int common_google_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_signin_btn_text_light_disabled = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_signin_btn_text_light_focused = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_signin_btn_text_light_pressed = 2131099655;
			
			// aapt resource value: 0x7f060011
			public const int common_google_signin_btn_tint = 2131099665;
			
			// aapt resource value: 0x7f06000b
			public const int notification_action_color_filter = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int notification_icon_bg_color = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int notification_material_background_media_default_color = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int primary_text_default_material_dark = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int ripple_material_light = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int secondary_text_default_material_dark = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int secondary_text_default_material_light = 2131099662;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f07000a
			public const int compat_button_inset_horizontal_material = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int compat_button_inset_vertical_material = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int compat_button_padding_horizontal_material = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int compat_button_padding_vertical_material = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int compat_control_corner_material = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int fastscroll_default_thickness = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int fastscroll_margin = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int fastscroll_minimum_range = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int item_touch_helper_swipe_escape_max_velocity = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int item_touch_helper_swipe_escape_velocity = 2131165189;
			
			// aapt resource value: 0x7f07000f
			public const int notification_action_icon_size = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int notification_action_text_size = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int notification_big_circle_margin = 2131165201;
			
			// aapt resource value: 0x7f070007
			public const int notification_content_margin_start = 2131165191;
			
			// aapt resource value: 0x7f070012
			public const int notification_large_icon_height = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int notification_large_icon_width = 2131165203;
			
			// aapt resource value: 0x7f070008
			public const int notification_main_column_padding_top = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int notification_media_narrow_margin = 2131165193;
			
			// aapt resource value: 0x7f070014
			public const int notification_right_icon_size = 2131165204;
			
			// aapt resource value: 0x7f070006
			public const int notification_right_side_padding_top = 2131165190;
			
			// aapt resource value: 0x7f070015
			public const int notification_small_icon_background_padding = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int notification_small_icon_size_as_large = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int notification_subtext_size = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int notification_top_pad = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int notification_top_pad_large_text = 2131165209;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cameraicon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_full_open_on_phone = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_disabled = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_normal_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_focused = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_normal = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal_background = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_disabled = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_focused = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_normal = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal_background = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int defaultprofile = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int galleryicon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int googleg_disabled_color_18 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int googleg_standard_color_18 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int hrselfservice = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int login2 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int login3 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int login4 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int login5 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int neptunelogo = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int notification_action_background = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int notification_bg = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int notification_bg_low = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int notification_bg_low_normal = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int notification_bg_low_pressed = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int notification_bg_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int notification_bg_normal_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int notification_icon_background = 2130837541;
			
			// aapt resource value: 0x7f02002b
			public const int notification_template_icon_bg = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int notification_template_icon_low_bg = 2130837548;
			
			// aapt resource value: 0x7f020026
			public const int notification_tile_bg = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int notify_panel_notification_icon_bg = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int roundButton = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int selfservice = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int uploadicon = 2130837546;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08008c
			public const int ImageView1 = 2131230860;
			
			// aapt resource value: 0x7f08001f
			public const int absenteeism = 2131230751;
			
			// aapt resource value: 0x7f080074
			public const int action0 = 2131230836;
			
			// aapt resource value: 0x7f080071
			public const int action_container = 2131230833;
			
			// aapt resource value: 0x7f080078
			public const int action_divider = 2131230840;
			
			// aapt resource value: 0x7f080072
			public const int action_image = 2131230834;
			
			// aapt resource value: 0x7f080073
			public const int action_text = 2131230835;
			
			// aapt resource value: 0x7f080082
			public const int actions = 2131230850;
			
			// aapt resource value: 0x7f080006
			public const int adjust_height = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int adjust_width = 2131230727;
			
			// aapt resource value: 0x7f08000f
			public const int async = 2131230735;
			
			// aapt resource value: 0x7f08000c
			public const int auto = 2131230732;
			
			// aapt resource value: 0x7f080010
			public const int blocking = 2131230736;
			
			// aapt resource value: 0x7f08002f
			public const int btnCountHome = 2131230767;
			
			// aapt resource value: 0x7f080061
			public const int btnSubmit = 2131230817;
			
			// aapt resource value: 0x7f08001a
			public const int btnSubmitAbsReq = 2131230746;
			
			// aapt resource value: 0x7f08003e
			public const int btnSubmitLeaveExt = 2131230782;
			
			// aapt resource value: 0x7f080051
			public const int btnSubmitLeaveReq = 2131230801;
			
			// aapt resource value: 0x7f080046
			public const int btnSubmitLvRec = 2131230790;
			
			// aapt resource value: 0x7f080070
			public const int btnSubmitMedReq = 2131230832;
			
			// aapt resource value: 0x7f080075
			public const int cancel_action = 2131230837;
			
			// aapt resource value: 0x7f08004f
			public const int chkAllowance = 2131230799;
			
			// aapt resource value: 0x7f08007d
			public const int chronometer = 2131230845;
			
			// aapt resource value: 0x7f08000d
			public const int dark = 2131230733;
			
			// aapt resource value: 0x7f080018
			public const int edtDateAbsReq = 2131230744;
			
			// aapt resource value: 0x7f08006d
			public const int edtDateMedReq = 2131230829;
			
			// aapt resource value: 0x7f08004c
			public const int edtEndDate = 2131230796;
			
			// aapt resource value: 0x7f08003a
			public const int edtExtendTo = 2131230778;
			
			// aapt resource value: 0x7f08005b
			public const int edtLvlComment = 2131230811;
			
			// aapt resource value: 0x7f08006b
			public const int edtMedComment = 2131230827;
			
			// aapt resource value: 0x7f080060
			public const int edtPassword = 2131230816;
			
			// aapt resource value: 0x7f080019
			public const int edtReasonAbsReq = 2131230745;
			
			// aapt resource value: 0x7f08003d
			public const int edtReasonExt = 2131230781;
			
			// aapt resource value: 0x7f08006f
			public const int edtReasonMedReq = 2131230831;
			
			// aapt resource value: 0x7f080050
			public const int edtReasonReq = 2131230800;
			
			// aapt resource value: 0x7f080045
			public const int edtRecallDt = 2131230789;
			
			// aapt resource value: 0x7f08004b
			public const int edtStartDate = 2131230795;
			
			// aapt resource value: 0x7f08009d
			public const int edtTrnComment = 2131230877;
			
			// aapt resource value: 0x7f08008a
			public const int edtTxtReason = 2131230858;
			
			// aapt resource value: 0x7f08005e
			public const int edtUserId = 2131230814;
			
			// aapt resource value: 0x7f080084
			public const int end_padder = 2131230852;
			
			// aapt resource value: 0x7f080034
			public const int expandableListView1 = 2131230772;
			
			// aapt resource value: 0x7f08009f
			public const int expdLstVw1 = 2131230879;
			
			// aapt resource value: 0x7f080086
			public const int fab1 = 2131230854;
			
			// aapt resource value: 0x7f080087
			public const int fab2 = 2131230855;
			
			// aapt resource value: 0x7f080088
			public const int fab3 = 2131230856;
			
			// aapt resource value: 0x7f080011
			public const int forever = 2131230737;
			
			// aapt resource value: 0x7f08001b
			public const int home = 2131230747;
			
			// aapt resource value: 0x7f08007f
			public const int icon = 2131230847;
			
			// aapt resource value: 0x7f080083
			public const int icon_group = 2131230851;
			
			// aapt resource value: 0x7f080009
			public const int icon_only = 2131230729;
			
			// aapt resource value: 0x7f08005c
			public const int imageView1 = 2131230812;
			
			// aapt resource value: 0x7f08007e
			public const int info = 2131230846;
			
			// aapt resource value: 0x7f080012
			public const int italic = 2131230738;
			
			// aapt resource value: 0x7f080000
			public const int item_touch_helper_previous_elevation = 2131230720;
			
			// aapt resource value: 0x7f080021
			public const int leave = 2131230753;
			
			// aapt resource value: 0x7f080023
			public const int leaveExtension = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int leaveRecall = 2131230756;
			
			// aapt resource value: 0x7f080022
			public const int leaveRequest = 2131230754;
			
			// aapt resource value: 0x7f08000e
			public const int light = 2131230734;
			
			// aapt resource value: 0x7f08002a
			public const int linBase = 2131230762;
			
			// aapt resource value: 0x7f080001
			public const int line1 = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int line3 = 2131230722;
			
			// aapt resource value: 0x7f080016
			public const int linearLayout1 = 2131230742;
			
			// aapt resource value: 0x7f080028
			public const int linearLayout2 = 2131230760;
			
			// aapt resource value: 0x7f080026
			public const int linearLayout3 = 2131230758;
			
			// aapt resource value: 0x7f080057
			public const int linearLayout4 = 2131230807;
			
			// aapt resource value: 0x7f080090
			public const int linearLayout5 = 2131230864;
			
			// aapt resource value: 0x7f080092
			public const int linearLayout6 = 2131230866;
			
			// aapt resource value: 0x7f08008d
			public const int linearLayout7 = 2131230861;
			
			// aapt resource value: 0x7f080025
			public const int logout = 2131230757;
			
			// aapt resource value: 0x7f080077
			public const int media_actions = 2131230839;
			
			// aapt resource value: 0x7f08001d
			public const int medicalRequest = 2131230749;
			
			// aapt resource value: 0x7f080008
			public const int none = 2131230728;
			
			// aapt resource value: 0x7f080013
			public const int normal = 2131230739;
			
			// aapt resource value: 0x7f080081
			public const int notification_background = 2131230849;
			
			// aapt resource value: 0x7f08007a
			public const int notification_main_column = 2131230842;
			
			// aapt resource value: 0x7f080079
			public const int notification_main_column_container = 2131230841;
			
			// aapt resource value: 0x7f080029
			public const int profileImage = 2131230761;
			
			// aapt resource value: 0x7f080097
			public const int recyclerView1 = 2131230871;
			
			// aapt resource value: 0x7f080080
			public const int right_icon = 2131230848;
			
			// aapt resource value: 0x7f08007b
			public const int right_side = 2131230843;
			
			// aapt resource value: 0x7f0800ab
			public const int rvwWorkListViewer = 2131230891;
			
			// aapt resource value: 0x7f080015
			public const int scrollView1 = 2131230741;
			
			// aapt resource value: 0x7f080062
			public const int space1 = 2131230818;
			
			// aapt resource value: 0x7f08008b
			public const int space2 = 2131230859;
			
			// aapt resource value: 0x7f08006e
			public const int spnHospitalMedReq = 2131230830;
			
			// aapt resource value: 0x7f080037
			public const int spnLeaveExt = 2131230775;
			
			// aapt resource value: 0x7f080041
			public const int spnLeaveRec = 2131230785;
			
			// aapt resource value: 0x7f080049
			public const int spnLeaveReq = 2131230793;
			
			// aapt resource value: 0x7f08004e
			public const int spnReliefOfficer = 2131230798;
			
			// aapt resource value: 0x7f080096
			public const int spnrTrainingCode = 2131230870;
			
			// aapt resource value: 0x7f08000a
			public const int standard = 2131230730;
			
			// aapt resource value: 0x7f080076
			public const int status_bar_latest_event_content = 2131230838;
			
			// aapt resource value: 0x7f080003
			public const int text = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int text2 = 2131230724;
			
			// aapt resource value: 0x7f08002d
			public const int textView1 = 2131230765;
			
			// aapt resource value: 0x7f080089
			public const int textView2 = 2131230857;
			
			// aapt resource value: 0x7f08005d
			public const int textView3 = 2131230813;
			
			// aapt resource value: 0x7f080065
			public const int textView4 = 2131230821;
			
			// aapt resource value: 0x7f08005f
			public const int textView5 = 2131230815;
			
			// aapt resource value: 0x7f080068
			public const int textView7 = 2131230824;
			
			// aapt resource value: 0x7f080059
			public const int textView8 = 2131230809;
			
			// aapt resource value: 0x7f08009a
			public const int textView9 = 2131230874;
			
			// aapt resource value: 0x7f0800a4
			public const int textViewApprTypeHeader = 2131230884;
			
			// aapt resource value: 0x7f0800a8
			public const int textViewDateSentHeader = 2131230888;
			
			// aapt resource value: 0x7f0800a2
			public const int textViewMsgHeader = 2131230882;
			
			// aapt resource value: 0x7f0800a6
			public const int textViewSentByHeader = 2131230886;
			
			// aapt resource value: 0x7f0800a0
			public const int textViewWkFrgSerNo = 2131230880;
			
			// aapt resource value: 0x7f08007c
			public const int time = 2131230844;
			
			// aapt resource value: 0x7f080005
			public const int title = 2131230725;
			
			// aapt resource value: 0x7f08001e
			public const int trainingRequest = 2131230750;
			
			// aapt resource value: 0x7f080093
			public const int tvDepartment = 2131230867;
			
			// aapt resource value: 0x7f080091
			public const int tvDesignation = 2131230865;
			
			// aapt resource value: 0x7f08008f
			public const int tvGrade = 2131230863;
			
			// aapt resource value: 0x7f08008e
			public const int tvName = 2131230862;
			
			// aapt resource value: 0x7f08009e
			public const int tview1 = 2131230878;
			
			// aapt resource value: 0x7f080032
			public const int tvwAbsenteeism = 2131230770;
			
			// aapt resource value: 0x7f08002b
			public const int tvwChildHome = 2131230763;
			
			// aapt resource value: 0x7f08002c
			public const int tvwChildUserProfile = 2131230764;
			
			// aapt resource value: 0x7f08003c
			public const int tvwDurationExt = 2131230780;
			
			// aapt resource value: 0x7f080035
			public const int tvwHeadingLevReq = 2131230773;
			
			// aapt resource value: 0x7f080014
			public const int tvwHeadingMedReq = 2131230740;
			
			// aapt resource value: 0x7f08003f
			public const int tvwHeadingRecall = 2131230783;
			
			// aapt resource value: 0x7f080094
			public const int tvwHeadingTrnReq = 2131230868;
			
			// aapt resource value: 0x7f080042
			public const int tvwLvTypeRec = 2131230786;
			
			// aapt resource value: 0x7f080054
			public const int tvwLvlDesc = 2131230804;
			
			// aapt resource value: 0x7f080052
			public const int tvwLvlEmpName = 2131230802;
			
			// aapt resource value: 0x7f080053
			public const int tvwLvlEmpNo = 2131230803;
			
			// aapt resource value: 0x7f080056
			public const int tvwLvlEndDate = 2131230806;
			
			// aapt resource value: 0x7f080058
			public const int tvwLvlNoOfDays = 2131230808;
			
			// aapt resource value: 0x7f08005a
			public const int tvwLvlReason = 2131230810;
			
			// aapt resource value: 0x7f080055
			public const int tvwLvlStartDate = 2131230805;
			
			// aapt resource value: 0x7f080063
			public const int tvwMedEmpName = 2131230819;
			
			// aapt resource value: 0x7f080066
			public const int tvwMedHospital = 2131230822;
			
			// aapt resource value: 0x7f080067
			public const int tvwMedLimBal = 2131230823;
			
			// aapt resource value: 0x7f08006a
			public const int tvwMedReason = 2131230826;
			
			// aapt resource value: 0x7f080030
			public const int tvwMedReq = 2131230768;
			
			// aapt resource value: 0x7f080064
			public const int tvwMedReqDate = 2131230820;
			
			// aapt resource value: 0x7f080069
			public const int tvwMedUsed = 2131230825;
			
			// aapt resource value: 0x7f080017
			public const int tvwMsg = 2131230743;
			
			// aapt resource value: 0x7f080036
			public const int tvwMsgLeaveExt = 2131230774;
			
			// aapt resource value: 0x7f080040
			public const int tvwMsgLeaveRecall = 2131230784;
			
			// aapt resource value: 0x7f080048
			public const int tvwMsgLeaveReq = 2131230792;
			
			// aapt resource value: 0x7f08006c
			public const int tvwMsgMedReq = 2131230828;
			
			// aapt resource value: 0x7f080095
			public const int tvwMsgTrnReq = 2131230869;
			
			// aapt resource value: 0x7f08004d
			public const int tvwNoOfDays = 2131230797;
			
			// aapt resource value: 0x7f08004a
			public const int tvwNoOfDaysleft = 2131230794;
			
			// aapt resource value: 0x7f080085
			public const int tvwParentHome = 2131230853;
			
			// aapt resource value: 0x7f08003b
			public const int tvwRemainDaysExt = 2131230779;
			
			// aapt resource value: 0x7f080039
			public const int tvwResumeDtExt = 2131230777;
			
			// aapt resource value: 0x7f080044
			public const int tvwResumeRec = 2131230788;
			
			// aapt resource value: 0x7f080047
			public const int tvwStDateRec = 2131230791;
			
			// aapt resource value: 0x7f080043
			public const int tvwStartDtRec = 2131230787;
			
			// aapt resource value: 0x7f080038
			public const int tvwStrDtExt = 2131230776;
			
			// aapt resource value: 0x7f080099
			public const int tvwTrnDesc = 2131230873;
			
			// aapt resource value: 0x7f080098
			public const int tvwTrnEmpName = 2131230872;
			
			// aapt resource value: 0x7f08009b
			public const int tvwTrnNomBy = 2131230875;
			
			// aapt resource value: 0x7f08009c
			public const int tvwTrnReason = 2131230876;
			
			// aapt resource value: 0x7f080031
			public const int tvwTrnReq = 2131230769;
			
			// aapt resource value: 0x7f080033
			public const int tvwUserProfile = 2131230771;
			
			// aapt resource value: 0x7f080027
			public const int tvwWelcome = 2131230759;
			
			// aapt resource value: 0x7f08002e
			public const int tvwWkListVwr = 2131230766;
			
			// aapt resource value: 0x7f0800a9
			public const int tvwWkvDateSent = 2131230889;
			
			// aapt resource value: 0x7f0800aa
			public const int tvwWkvMsg = 2131230890;
			
			// aapt resource value: 0x7f0800a3
			public const int tvwWkvMsgInfo = 2131230883;
			
			// aapt resource value: 0x7f0800a7
			public const int tvwWkvSentBy = 2131230887;
			
			// aapt resource value: 0x7f0800a1
			public const int tvwWkvSerialNo = 2131230881;
			
			// aapt resource value: 0x7f0800a5
			public const int tvwWkvType = 2131230885;
			
			// aapt resource value: 0x7f080020
			public const int userProfile = 2131230752;
			
			// aapt resource value: 0x7f08000b
			public const int wide = 2131230731;
			
			// aapt resource value: 0x7f08001c
			public const int wkListViewer = 2131230748;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050001
			public const int cancel_button_image_alpha = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int status_bar_notification_info_maxnum = 2131034114;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Absenteeism = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AppMenu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BaseLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ChildItems = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ChildItemUserProfile = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Home = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int LeaveExtension = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int LeaveRecall = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int LeaveRequest = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int LvlApprovalDialogLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Main = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int MedApprovalDialogLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int MedicalRequest = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_action = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_action_tombstone = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_media_action = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int notification_media_cancel_action = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int notification_template_big_media = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int notification_template_big_media_custom = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int notification_template_big_media_narrow = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int notification_template_big_media_narrow_custom = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int notification_template_custom_big = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int notification_template_icon_group = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int notification_template_lines_media = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int notification_template_media = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int notification_template_media_custom = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int notification_template_part_chronometer = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int notification_template_part_time = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int ParentItem = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int ParentItemUserProfile = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int ProfilePicDialog = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int TrainingNominateDialog = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int TrainingRecyclerRows = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int TrainingRequestLayout = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int TrnApprovalDialogLayout = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int UserProfile = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int WorkListFragment = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int WorkListLayout = 2130903077;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04001a
			public const int app_name = 2130968602;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_enable_button = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_enable_text = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_enable_title = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_install_button = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_install_text = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_install_title = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_notification_ticker = 2130968590;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_unknown_issue = 2130968583;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_play_services_unsupported_text = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_update_button = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int common_google_play_services_update_text = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_update_title = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_updating_text = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_wear_update_text = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int common_open_on_phone = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int common_signin_button_text = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int common_signin_button_text_long = 2130968599;
			
			// aapt resource value: 0x7f040002
			public const int default_web_client_id = 2130968578;
			
			// aapt resource value: 0x7f040018
			public const int fcm_fallback_notification_channel_label = 2130968600;
			
			// aapt resource value: 0x7f040003
			public const int firebase_database_url = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int gcm_defaultSenderId = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int google_api_key = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int google_app_id = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int google_crash_reporting_api_key = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int google_storage_bucket = 2130968582;
			
			// aapt resource value: 0x7f040019
			public const int status_bar_notification_info_overflow = 2130968601;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f09000c
			public const int App_Theme = 2131296268;
			
			// aapt resource value: 0x7f090005
			public const int TextAppearance_Compat_Notification = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int TextAppearance_Compat_Notification_Info = 2131296262;
			
			// aapt resource value: 0x7f090000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131296256;
			
			// aapt resource value: 0x7f09000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131296267;
			
			// aapt resource value: 0x7f090004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131296260;
			
			// aapt resource value: 0x7f090001
			public const int TextAppearance_Compat_Notification_Media = 2131296257;
			
			// aapt resource value: 0x7f090007
			public const int TextAppearance_Compat_Notification_Time = 2131296263;
			
			// aapt resource value: 0x7f090002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131296258;
			
			// aapt resource value: 0x7f090008
			public const int TextAppearance_Compat_Notification_Title = 2131296264;
			
			// aapt resource value: 0x7f090003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131296259;
			
			// aapt resource value: 0x7f090009
			public const int Widget_Compat_NotificationActionContainer = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int Widget_Compat_NotificationActionText = 2131296266;
			
			// aapt resource value: 0x7f090016
			public const int styleBtnSubmit = 2131296278;
			
			// aapt resource value: 0x7f09000d
			public const int styleEdt = 2131296269;
			
			// aapt resource value: 0x7f090014
			public const int styleEdtDate = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int styleEdtReason = 2131296277;
			
			// aapt resource value: 0x7f090010
			public const int styleSpinner = 2131296272;
			
			// aapt resource value: 0x7f09000e
			public const int styleTvw = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int styleTvwMainHeader = 2131296271;
			
			// aapt resource value: 0x7f090011
			public const int styleTvwMainMessage = 2131296273;
			
			// aapt resource value: 0x7f090013
			public const int styleTvwSubHeader = 2131296275;
			
			// aapt resource value: 0x7f090012
			public const int styleTvwSubHeaderFirst = 2131296274;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleImageView = new int[] {
					2130771992,
					2130771993,
					2130771994,
					2130771995};
			
			// aapt resource value: 1
			public const int CircleImageView_civ_border_color = 1;
			
			// aapt resource value: 2
			public const int CircleImageView_civ_border_overlay = 2;
			
			// aapt resource value: 0
			public const int CircleImageView_civ_border_width = 0;
			
			// aapt resource value: 3
			public const int CircleImageView_civ_fill_color = 3;
			
			public static int[] FontFamily = new int[] {
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771989,
					2130771990,
					2130771991};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 6
			public const int RecyclerView_fastScrollEnabled = 6;
			
			// aapt resource value: 9
			public const int RecyclerView_fastScrollHorizontalThumbDrawable = 9;
			
			// aapt resource value: 10
			public const int RecyclerView_fastScrollHorizontalTrackDrawable = 10;
			
			// aapt resource value: 7
			public const int RecyclerView_fastScrollVerticalThumbDrawable = 7;
			
			// aapt resource value: 8
			public const int RecyclerView_fastScrollVerticalTrackDrawable = 8;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
